kind: pipeline
name: default

steps:
- name: Maven Build
  image: maven:3.6.3-jdk-11
  commands:
  - mvn verify
  volumes:
  - name: docker
    path: /var/run/docker.sock

volumes:
- name: docker
  host:
    path: /var/run/docker.sock 
